"""
Shared honesty-discipline content for the `tj route` static-export generators.

Every router-config export TokenJam emits must carry, as comments where the
format allows: the evidence level per rule, the derivation window, the
derived-at date, and the no-quality-claim caveat (`MODEL_DOWNGRADE_CAVEAT`,
which the `DowngradeFinding` dataclass already carries). This module is the
single place those strings live, so CLAUDE.md Critical Rule 14 (never claim
quality equivalence; rules are advisory L1, never "safe") can be audited in
one spot.

Generators call these helpers for the comment *text* (prefix-free lines) and
apply their own format's comment marker (`//` for JSONC, `#` for YAML).
"""
from __future__ import annotations

# Evidence level for every statically-derived downgrade rule. L1 = a structural
# match across recent sessions; explicitly NOT a measured quality-equivalence
# claim. There is no "safe" level in the static-export plane.
EVIDENCE_LEVEL = "L1"
EVIDENCE_DESC = "structural match, review before applying"


def rule_evidence_comment() -> str:
    """One-line per-rule evidence annotation (no comment marker)."""
    return f"evidence: {EVIDENCE_LEVEL} — {EVIDENCE_DESC}"


def header_lines(
    *,
    target: str,
    generated_at: str,
    since: str,
    until: str,
    agent_id: str | None,
    plan_tier: str,
    pricing_mode: str,
) -> list[str]:
    """Provenance header (prefix-free comment lines) for an export.

    Records what produced the file, the derivation window, the derived-at
    timestamp, the scope, the plan tier, and the (uniform L1) evidence level.
    """
    scope = f"agent_id={agent_id}" if agent_id else "all agents"
    return [
        f"Generated by `tj route export --target {target}`",
        f"Derived at: {generated_at}",
        f"Derivation window: {since} -> {until}",
        f"Scope: {scope}",
        f"Plan tier: {plan_tier} ({pricing_mode} pricing)",
        f"Evidence level: {EVIDENCE_LEVEL} ({EVIDENCE_DESC})",
    ]


def caveat_lines(caveat: str) -> list[str]:
    """Mandatory honesty caveat block (prefix-free comment lines).

    ``caveat`` is the finding's own caveat string (``MODEL_DOWNGRADE_CAVEAT``),
    embedded verbatim. The surrounding text frames every rule as advisory L1 —
    a structural heuristic to review, never "safe" to apply blindly.
    """
    return [
        "STRUCTURAL HEURISTIC ONLY — review before applying.",
        "",
        caveat,
        "",
        "Each rule is evidence level L1: a structural match across recent",
        "sessions, NOT a validated quality-equivalence claim. Test on a few",
        "real sessions before trusting it broadly. These rules are advisory —",
        "never \"safe\".",
        "",
        "TokenJam does not enforce these rules. You apply them by editing your",
        "own router config (claude-code-router, LiteLLM) by hand.",
        "",
        "See https://tokenjam.dev/products/downsize for details.",
    ]


def select_figure_value(
    *,
    pricing_mode: str,
    monthly_savings_usd: float,
    monthly_tokens_in_candidates: int,
) -> tuple[str, object]:
    """Pick the plan-tier-appropriate savings figure for a rule.

    Mirrors ``claude_code.py``: API users get a dollar/month estimate;
    subscription/local users get tokens-freed (never dollars against a flat
    fee); unknown-plan users get a reconfigure note instead of a number.

    Returns ``(key, value)`` for the generator to render in its own syntax.
    """
    if pricing_mode == "api":
        return "estimated_savings_usd_month", monthly_savings_usd
    if pricing_mode in {"subscription", "local"}:
        return "estimated_tokens_freed", monthly_tokens_in_candidates
    return (
        "note",
        "configure plan tier with `tj onboard --reconfigure` to see "
        "savings projections",
    )
