"""The persona POPULATION scope — which rows an analyzer pass may look at.

Two different things wear the word "persona" in this package, and conflating
them is the defect this module exists to close:

* the **dispatch gate** (``runner.PERSONA_DISABLED_ANALYZERS``) decides WHICH
  ANALYZERS run for a persona — an analyzer with no fix that persona can apply
  is never invoked;
* the **population scope**, here, decides WHICH ROWS feed the ones that do run.

The gate alone leaves every surviving analyzer computing its dollar figure over
the whole mixed corpus, so a reader who has asked to see only their SDK traffic
is shown a number produced almost entirely by Claude Code sessions. A figure
published under a persona label has to be computed over that persona's rows.

Only ``claude-code`` and ``sdk`` narrow anything. ``mixed`` / ``unknown`` /
``None`` scope to the whole corpus — the same conservative default
``runner.disabled_analyzers_for_persona`` takes for an unclassified window, and
the same one ``GET /sessions`` takes for those personas.

The predicate itself is generated by ``alerts.interactive_coding_agent_sql``
from the one prefix tuple ``alerts.is_interactive_coding_agent`` reads, so the
SQL side and the Python side cannot disagree. Never write a second bucketing
rule here or at a call site.
"""
from __future__ import annotations

from tokenjam.core.alerts import interactive_coding_agent_sql

#: The personas that actually narrow the population. A persona outside this set
#: scopes to everything; callers test membership rather than re-listing it.
SCOPING_PERSONAS: tuple[str, ...] = ("claude-code", "sdk")


def persona_scopes_population(persona_scope: str | None) -> bool:
    """True when ``persona_scope`` narrows the rows an analyzer may read."""
    return persona_scope in SCOPING_PERSONAS


def persona_agent_clause(
    persona_scope: str | None, column: str = "agent_id",
) -> str | None:
    """A SQL boolean clause scoping ``column`` to ``persona_scope``'s rows.

    ``None`` means "no narrowing" — the caller appends nothing. The clause is
    parameter-free (it is generated from a fixed prefix tuple, not from user
    input), so a caller can append it to a ``clauses`` list without disturbing
    its positional ``$n`` numbering.
    """
    if persona_scope == "claude-code":
        return interactive_coding_agent_sql(column)
    if persona_scope == "sdk":
        return f"NOT ({interactive_coding_agent_sql(column)})"
    return None


def add_persona_clause(
    clauses: list[str], persona_scope: str | None, column: str = "agent_id",
) -> None:
    """Append the population scope to ``clauses``, if there is one.

    The one line every analyzer's WHERE-clause builder carries. It is written as
    a mutator over the existing list — rather than a string a caller has to
    remember to ``AND`` in — because the failure mode being designed against is
    an analyzer that silently forgets the scope and publishes a whole-corpus
    figure under a persona label.
    """
    clause = persona_agent_clause(persona_scope, column)
    if clause is not None:
        clauses.append(clause)
